spring.application.name=demo
server.port=8081

# Database Configuration

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

# Show SQL queries
spring.jpa.show-sql=true

# JWT Configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SUPABASE_JWT_JWK_SET_URI}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SUPABASE_JWT_ISSUER_URI}

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG

stripe.secret.key=${STRIPE_SECRET_KEY}